name: FinNews Bot Scheduler

on:
  schedule:
    # 每 10 分鐘執行一次（UTC 時間）
    - cron: '*/10 * * * *'
  workflow_dispatch: # 允許手動觸發

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb
        # 安裝 Chrome
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run scraper
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        YAHOO_FINANCE_URL: https://finance.yahoo.com/topic/stock-market-news
        SCRAPER_TIMEOUT: 30
        DISPLAY: :99
      run: |
        # 啟動虛擬顯示器（Selenium 需要）
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3
        # 執行爬蟲
        python run_scraper.py
    
    - name: Upload debug screenshots (if any)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: debug-screenshots-${{ github.run_number }}
        path: debug_pages/
        retention-days: 7 