name: Smart Pusher

on:
  schedule:
    # 台灣推送時間（08:00, 13:00, 20:00 ±30分鐘）對應的 UTC 時間
    # 台灣 08:00 = UTC 00:00，台灣 13:00 = UTC 05:00，台灣 20:00 = UTC 12:00
    - cron: '0,15,30,45 0,5,12 * * *'  # 每個推送時段的前後 45 分鐘內，每 15 分鐘執行一次
  workflow_dispatch: # 允許手動觸發

jobs:
  smart-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    # Smart Pusher 不需要 Chrome，只處理已存儲的文章
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run smart pusher
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}
      run: |
        # 執行智能推送器（基於已存儲的文章）
        python run_smart_pusher.py
    
    # Smart Pusher 不需要上傳截圖 